import { test, expect, type Page } from "@playwright/test";
import { PNG } from "pngjs";

// The service worker is generated by the production build, so these tests run
// against `vite preview` (see playwright.config.ts) rather than the dev server.
const origin = "http://127.0.0.1:4173";
test.use({ baseURL: origin });

async function loadOnline(page: Page) {
  await page.goto("/");
  await expect(page.getByLabel("Offline status")).toContainText(
    "Stored for offline use",
    { timeout: 30_000 },
  );
}

test("reloads offline, restores the saved project, opens a stored sample and explains unstored ones", async ({
  page,
  context,
}) => {
  const foreign: string[] = [];
  context.on("request", (request) => {
    if (!request.url().startsWith(origin) || request.method() !== "GET")
      foreign.push(request.url());
  });
  await loadOnline(page);
  const source = new PNG({ width: 40, height: 40 });
  for (let i = 0; i < source.data.length; i += 4)
    source.data.set([100, 60, 30, 255], i);
  await page.getByLabel("Choose image").setInputFiles({
    name: "private.png",
    mimeType: "image/png",
    buffer: PNG.sync.write(source),
  });
  const exposure = page.getByRole("spinbutton", { name: "Exposure in stops" });
  await exposure.fill("1.25");
  await exposure.press("Enter");
  const preview = page.getByLabel("Graded image preview");
  await expect(preview).toHaveAttribute("width", "40");
  const saved = await preview.screenshot();
  await page.getByRole("button", { name: "Save project", exact: true }).click();
  await expect(page.getByLabel("Project status")).toContainText(
    "Saved on this device",
  );

  await page.getByRole("button", { name: "Browse samples" }).click();
  const gallery = page.getByRole("region", { name: "Bundled log samples" });
  const desk = gallery.getByRole("button", {
    name: "Desk by stained-glass window",
    exact: true,
  });
  const tree = gallery.getByRole("button", {
    name: "Sunlit tree",
    exact: true,
  });
  await expect(desk).not.toContainText("Stored offline");
  await desk.click();
  await expect(desk).toHaveAttribute("aria-pressed", "true");
  await expect(desk).toContainText("Stored offline");
  await expect(tree).not.toContainText("Stored offline");

  await context.setOffline(true);
  await page.reload();
  await expect(page.getByLabel("Offline status")).toContainText("Offline");
  await expect(page.getByLabel("Project status")).toContainText(
    "Restored from this device",
  );
  await expect(page.getByText("private.png", { exact: true })).toBeVisible();
  await page.locator('.react-flow__node[data-id="exposure"]').click();
  await expect(exposure).toHaveValue("1.25");
  expect(await preview.screenshot()).toEqual(saved);

  await page.getByRole("button", { name: "Browse samples" }).click();
  await expect(desk).toContainText("Stored offline");
  const offlineSamples = page.getByRole("group", { name: "Offline samples" });
  await expect(offlineSamples.getByRole("button")).toBeDisabled();
  await desk.click();
  await expect(desk).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByLabel("Sample provenance")).toBeVisible();
  await expect(page.getByRole("alert")).toHaveCount(0);
  await exposure.fill("-1.5");
  await exposure.press("Enter");
  const graded = await preview.screenshot();

  await tree.click();
  await expect(page.getByRole("alert")).toContainText("offline");
  await expect(page.getByRole("alert")).toContainText("Sunlit tree");
  await expect(desk).toHaveAttribute("aria-pressed", "true");
  await expect(exposure).toHaveValue("-1.50");
  expect(await preview.screenshot()).toEqual(graded);
  await page.getByRole("button", { name: "Save project", exact: true }).click();
  await expect(page.getByLabel("Project status")).toContainText(
    "Saved on this device",
  );

  await context.setOffline(false);
  await tree.click();
  await expect(tree).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("alert")).toHaveCount(0);
  await expect(tree).toContainText("Stored offline");
  expect(foreign).toEqual([]);
});

test("store all samples offline, then open each one offline", async ({
  page,
  context,
}) => {
  await loadOnline(page);
  await page.getByRole("button", { name: "Browse samples" }).click();
  const gallery = page.getByRole("region", { name: "Bundled log samples" });
  const offlineSamples = page.getByRole("group", { name: "Offline samples" });
  await offlineSamples.getByRole("button").click();
  await expect(offlineSamples.getByRole("status")).toContainText(
    "All 9 samples are stored offline",
    { timeout: 120_000 },
  );
  await context.setOffline(true);
  await page.reload();
  await expect(page.getByLabel("Offline status")).toContainText("Offline");
  await page.getByRole("button", { name: "Browse samples" }).click();
  await expect(gallery.getByText("Stored offline")).toHaveCount(9);
  for (const name of [
    "Sunlit tree",
    "Cowboy Town Saloon — photographed neutral and colour chart",
  ]) {
    const choice = gallery.getByRole("button", { name, exact: true });
    await choice.click();
    await expect(choice).toHaveAttribute("aria-pressed", "true");
    await expect(page.getByRole("alert")).toHaveCount(0);
  }
});

test("a new application version waits for an explicit reload and keeps saved work", async ({
  page,
}) => {
  await loadOnline(page);
  const exposure = page.getByRole("spinbutton", { name: "Exposure in stops" });
  await exposure.fill("2");
  await exposure.press("Enter");
  await page.getByRole("button", { name: "Save project", exact: true }).click();
  await expect(page.getByLabel("Project status")).toContainText(
    "Saved on this device",
  );
  await exposure.fill("3");
  await exposure.press("Enter");
  // A different worker URL on the same scope installs like a deployed update.
  await page.evaluate(() => navigator.serviceWorker.register("/sw.js?next"));
  const status = page.getByLabel("Offline status");
  await expect(status).toContainText("update", { timeout: 30_000 });
  await expect(status).toContainText("Save your project");
  await expect(exposure).toHaveValue("3.00");
  await status.getByRole("button", { name: "Reload to update" }).click();
  await expect(page.getByLabel("Project status")).toContainText(
    "Restored from this device",
  );
  await page.locator('.react-flow__node[data-id="exposure"]').click();
  await expect(exposure).toHaveValue("2.00");
  // The app re-registers /sw.js, which the browser treats as a further update
  // of this artificial second URL; a real deployment keeps one script URL.
  expect(
    await page.evaluate(
      () => navigator.serviceWorker.controller?.scriptURL ?? "",
    ),
  ).toContain("sw.js?next");
});
