"""Regenerate fixed RGB/XYZ and Bradford matrices: python3 scripts/colour-matrices.py.
Chromaticities: ITU-R BT.709-6, BT.2020-2, SMPTE RP 431-2,
ARRI Log C Usage in VFX (2017-03-09), Sony S-Log3 Technical Summary V1.0.
See docs/colour-management.md. All matrices are row-major, relative white Y=1.
"""
from pathlib import Path
import json


def mul(a, b):
    return [[sum(x * y for x, y in zip(row, col)) for col in zip(*b)] for row in a]


def inv(a):
    m = [row[:] + [float(i == j) for j in range(3)] for i, row in enumerate(a)]
    for i in range(3):
        pivot = m[i][i]
        m[i] = [v / pivot for v in m[i]]
        for j in range(3):
            if j != i:
                scale = m[j][i]
                m[j] = [x - scale * y for x, y in zip(m[j], m[i])]
    return [row[3:] for row in m]


def xyz(x, y):
    return [[x / y], [1.0], [(1 - x - y) / y]]


def diagonal(v):
    return [[v[i][0] if i == j else 0 for j in range(3)] for i in range(3)]


def rgb_matrix(points, white):
    columns = [xyz(*p) for p in points]
    m = [[c[i][0] for c in columns] for i in range(3)]
    return mul(m, diagonal(mul(inv(m), white)))


p3 = [(0.680, 0.320), (0.265, 0.690), (0.150, 0.060)]
d65 = xyz(0.3127, 0.3290)
dci = xyz(0.3140, 0.3510)
spaces = {
    'rec709': ([(0.640, 0.330), (0.300, 0.600), (0.150, 0.060)], d65),
    'rec2020': ([(0.708, 0.292), (0.170, 0.797), (0.131, 0.046)], d65),
    'display-p3': (p3, d65),
    'dci-p3': (p3, dci),
    'arri-wide-gamut3': ([(0.6840, 0.3130), (0.2210, 0.8480), (0.0861, -0.1020)], d65),
    'sgamut3-cine': ([(0.7660, 0.2750), (0.2250, 0.8000), (0.0890, -0.0870)], d65),
}
b = [[0.8951, 0.2664, -0.1614], [-0.7502, 1.7135, 0.0367], [0.0389, -0.0685, 1.0296]]
cones_d65, cones_dci = mul(b, d65), mul(b, dci)
cat = mul(mul(inv(b), diagonal([[x[0] / y[0]] for x, y in zip(cones_d65, cones_dci)])), b)
matrices = {name: {'toXYZ': rgb_matrix(p, w), 'fromXYZ': inv(rgb_matrix(p, w))} for name, (p, w) in spaces.items()}
text = '// Generated by scripts/colour-matrices.py; do not hand-edit. Row-major.\n'
text += 'export const gamutMatrices = ' + json.dumps(matrices, indent=2) + ' as const;\n'
text += 'export const dciToD65 = ' + json.dumps(cat) + ';\n'
text += 'export const d65ToDci = ' + json.dumps(inv(cat)) + ';\n'
Path('src/engine/colourMatrices.ts').write_text(text)
